# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 08:58
from __future__ import unicode_literals

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[contact.models.validate_name])),
                ('title', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=400, validators=[contact.models.validate_len])),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
