# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[restaurant.models.validate_name])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to=b'get_upload_file_name')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[restaurant.models.validate_name])),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField(max_length=400, validators=[restaurant.models.validate_len])),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=10, validators=[restaurant.models.validate_name])),
                ('booking_date', models.DateField()),
                ('duration_booking_in_hours', models.PositiveIntegerField()),
                ('class_of_booking', models.CharField(max_length=100)),
                ('number_of_people', models.CharField(max_length=100)),
                ('is_it_a_special_occasion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Select', models.CharField(max_length=100, validators=[restaurant.models.validate_recepie])),
                ('Flavour', models.CharField(max_length=100, validators=[restaurant.models.validate_recepie])),
                ('Toppings', models.CharField(max_length=100, validators=[restaurant.models.validate_recepie])),
                ('Describe', models.TextField(max_length=100, validators=[restaurant.models.validate_describe])),
                ('photo', models.ImageField(upload_to=b'orders')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', restaurant.models.IntegerRangeField()),
                ('name_in_card', models.CharField(max_length=100, validators=[restaurant.models.validate_name])),
                ('expiry_date', models.DateField()),
                ('email_id', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('fullname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='recepie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepie_name', models.CharField(max_length=15)),
                ('ingredients', models.TextField(max_length=200)),
                ('reference', models.URLField(blank=True)),
                ('emailid', models.EmailField(max_length=254)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16, validators=[restaurant.models.validate_pass])),
                ('confirm_password', models.CharField(max_length=16, validators=[restaurant.models.validate_pass])),
                ('emailid', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to=restaurant.models.get_upload_file_name)),
            ],
        ),
    ]
