# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderspecial',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'orders'),
        ),
    ]
