# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderspecial',
            name='Toppings',
            field=models.CharField(default='Cheese', max_length=100),
            preserve_default=False,
        ),
    ]
