# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_orderspecial_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderspecial',
            name='Describe',
            field=models.TextField(default=datetime.datetime(2016, 7, 28, 16, 56, 52, 134007, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
