# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_orderspecial_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(max_length=16)),
                ('name_in_card', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='orderspecial',
            name='Describe',
            field=models.TextField(max_length=100, validators=[restaurant.models.validate_describe]),
        ),
    ]
