# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 15:41
from __future__ import unicode_literals

from django.db import migrations
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20160821_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='added_user',
            name='price',
            field=restaurant.models.IntegerRangeField(default='3'),
            preserve_default=False,
        ),
    ]
