# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20160729_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_process',
            name='card_number',
            field=restaurant.models.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='payment_process',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='payment_process',
            name='name_in_card',
            field=models.CharField(max_length=100, validators=[restaurant.models.validate_name]),
        ),
    ]
