# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_added_user_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_new',
        ),
        migrations.RemoveField(
            model_name='added_user',
            name='price',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Comment'),
        ),
    ]
