# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20160729_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='recepie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepie_name', models.CharField(max_length=15)),
                ('ingredients', models.TextField(max_length=200)),
                ('reference', models.URLField(blank=True)),
                ('emailid', models.EmailField(max_length=254)),
                ('date', models.DateField()),
            ],
        ),
    ]
