# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20160823_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='firstname',
            field=models.CharField(default='\x1b[A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='lastname',
            field=models.CharField(default='josh', max_length=10),
            preserve_default=False,
        ),
    ]
