# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_recepie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[restaurant.models.validate_name])),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=400, validators=[restaurant.models.validate_len])),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
