# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_contact_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_table', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('duration_booking_in_hours', models.IntegerField()),
                ('class_of_booking', models.CharField(max_length=100)),
                ('number_of_people', models.CharField(max_length=100)),
                ('is_it_a_special_occasion', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contact_all',
            name='query',
            field=models.TextField(max_length=400, validators=[restaurant.models.validate_len]),
        ),
    ]
