# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20160731_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_table',
            name='number_of_table',
        ),
        migrations.AddField(
            model_name='order_table',
            name='table_name',
            field=models.CharField(default='josh', max_length=10, validators=[restaurant.models.validate_name]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_table',
            name='duration_booking_in_hours',
            field=models.PositiveIntegerField(),
        ),
    ]
