# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20160825_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
