# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mode',
            old_name='q',
            new_name='mode_of_payement',
        ),
        migrations.AlterField(
            model_name='orderspecial',
            name='Flavour',
            field=models.CharField(max_length=100, validators=[restaurant.models.validate_recepie]),
        ),
        migrations.AlterField(
            model_name='orderspecial',
            name='Select',
            field=models.CharField(max_length=100, validators=[restaurant.models.validate_recepie]),
        ),
        migrations.AlterField(
            model_name='orderspecial',
            name='Toppings',
            field=models.CharField(max_length=100, validators=[restaurant.models.validate_recepie]),
        ),
    ]
