# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 11:19
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_login'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderspecial',
            managers=[
                ('delete', django.db.models.manager.Manager()),
            ],
        ),
    ]
