# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20160803_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16, validators=[restaurant.models.validate_pass])),
                ('confirm_password', models.CharField(max_length=16, validators=[restaurant.models.validate_pass])),
                ('emailid', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderspecial',
            managers=[
            ],
        ),
    ]
